name: Homelab Monitoring

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  schedule:
    # Run every hour
    - cron: '0 * * * *'

jobs:
  test:
    name: Run Monitoring Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Unlock git-crypt
        uses: sliteteam/github-action-git-crypt-unlock@1.3.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Install Playwright browsers
        run: yarn playwright install chromium --with-deps

      - name: Run Playwright tests
        run: yarn test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

      - name: Send Pushover notification
        uses: umahmood/pushover-actions@main
        if: failure()
        env:
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
        with:
          status: ${{ job.status }}
          title: 'Homelab Monitoring'
          message: 'Monitoring tests failed - ${{ github.actor }}'
